name: Docker Image CI

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read  # Necessario per checkout

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug build info
        run: |
          echo "Building repo for: ${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA ($DOCKER_TARGET_PLATFORM)"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |        
          docker buildx build \
          --platform ${{ env.DOCKER_TARGET_PLATFORM }} \
          --tag docker.io/${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA \
          --tag docker.io/${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_REPOSITORY }}:latest \
          --file ./Dockerfile \
          --push .
